CREATE TABLE Users
(
Id BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Username VARCHAR(30) UNIQUE NOT NULL,
[Password] VARCHAR(26) NOT NULL,
ProfilePicture VARCHAR(MAX),
LastLoginTime DATETIME,
IsDeleted BIT
)

INSERT INTO Users
VALUES
('Ivan','123444','image','12/12/2022',0),
('Petar','234441','image','3/12/2022',1),
('Yoan','123544','image','06/07/2021',0),
('Zhulieta','123251','image','12/19/2021',0),
('Maria','123111','image','12/22/2022',1)

SELECT * FROM Users

SELECT TABLE_NAME,
       CONSTRAINT_TYPE,CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME='Users';

ALTER TABLE Users
DROP CONSTRAINT PK__Users__3214EC0777C9A7E5

ALTER TABLE Users
ADD CONSTRAINT PK_IdUsername PRIMARY KEY (Id, Username)

ALTER TABLE Users
ADD CONSTRAINT CH_Password5Symbols 
CHECK(LEN([Password])>5)

ALTER TABLE Users
ADD CONSTRAINT Default_LastLoginTime DEFAULT GETDATE() FOR LastLoginTime

ALTER TABLE Users
DROP CONSTRAINT PK_IdUsername

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT CH_Username3Symbols 
CHECK(len([Username])>3)
