
CREATE TABLE Subjects
(
SubjectID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SubjectName VARCHAR(50) NOT NULL
)

CREATE TABLE Majors
(
MajorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Name] VARCHAR(50)
)

CREATE TABLE Students
(
StudentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
StudentNumber VARCHAR(20) NOT NULL,
StudentName VARCHAR(50)NOT NULL,
MajorID INT FOREIGN KEY REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
PaymentID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PaymentDate DATE NOT NULL,
PaymentAmount DECIMAL(15,2) NOT NULL,
StudentID INT FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Agenda
(
StudentID INT FOREIGN KEY REFERENCES Students(StudentID),
SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID),
PRIMARY KEY(StudentID,SubjectID)
)

